In [2]:
my_list = [1,2,3]

In [3]:
my_list

[1, 2, 3]

In [1]:
import numpy as np

In [7]:
my_list = np.array([1,2,3])
my_list

array([1, 2, 3])

In [9]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]
arr = np.array(my_mat)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [22]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [39]:
np.linspace(0,500,3)         #1st argument is for starting point 2nd is for last point and 3rd is for giving it in equal parts

array([  0., 250., 500.])

In [41]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [79]:
np.random.rand(10,2)

array([[0.76731715, 0.60389267],
       [0.15157018, 0.35522439],
       [0.28412757, 0.16780504],
       [0.90767931, 0.7748758 ],
       [0.73174462, 0.14591358],
       [0.61974237, 0.62954787],
       [0.75046848, 0.36459247],
       [0.35619824, 0.81318454],
       [0.57308294, 0.15359013],
       [0.38977359, 0.2057948 ]])

In [116]:
np.random.randn(2,2)

array([[-1.10915771, -1.2308588 ],
       [-1.4561104 ,  0.58327316]])

In [210]:
ar = np.random.randint(0,10,10)
ar

array([8, 7, 8, 4, 4, 4, 5, 5, 5, 2])

In [200]:
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [202]:
a.max()

9

In [203]:
a.min()

1

In [204]:
a.argmax()

8

In [205]:
a.argmin()

0

In [214]:
ar.shape

(10,)

In [216]:
ar.dtype

dtype('int32')

In [6]:
aad = np.arange(0,11)
aad

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
aad[8]

8

In [26]:
aad[1:5]

array([1, 2, 3, 4])

In [27]:
aad[5:]

array([ 5,  6,  7,  8,  9, 10])

In [35]:
a = np.random.randint(0,20,10)
b = a

In [36]:
b

array([ 7,  3,  5, 12,  7, 14, 13, 19,  1, 17])

In [37]:
b[b>3]

array([ 7,  5, 12,  7, 14, 13, 19, 17])

In [39]:
aad[aad>8]

array([ 9, 10])

In [41]:
b[]

19

In [42]:
type(aad)

numpy.ndarray

In [48]:
bc = (1,2,3,4,5,6,7,8,9,10)
bc

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

In [55]:
for i in bc:
    if i>5:
        print(i)

6
7
8
9
10


In [57]:
ba = [1,2,3,4,5,6,7,8,9]
type(ba)

list

In [60]:
ca = np.array(ba)

In [63]:
ca>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [64]:
adc = np.arange(0,11)

In [65]:
adc

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
adc.max()

10

In [67]:
np.max(adc)

10

In [68]:
np.sin(adc)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [69]:
np.log(adc)

c:\program files (x86)\python3.7\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [70]:
np.tan(adc)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566,
        0.64836083])

In [73]:
mat = np.arange(1,10).reshape(3,3)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
np.sum(mat, axis=0)

array([12, 15, 18])

In [ ]:
np.sum()

In [2]:
np.ones((10,1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])