In [1]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [1]:
import numpy as np

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_arr = [[1,2,3], [4,5,6], [7,8,9]]
np.array(my_arr)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
a = np.arange(1,12,2)
a

array([ 1,  3,  5,  7,  9, 11])

In [11]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.linspace(0,250,3)

array([  0., 125., 250.])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.random.rand(10,2)

array([[0.93232322, 0.00208867],
       [0.73395777, 0.36489755],
       [0.6886296 , 0.71852226],
       [0.84048777, 0.69760611],
       [0.36773634, 0.53960456],
       [0.37026675, 0.14888811],
       [0.36157038, 0.43474541],
       [0.27211624, 0.69985161],
       [0.59457213, 0.70794711],
       [0.40653759, 0.80617381]])

In [20]:
np.random.randn(10,2)

array([[ 1.04425555,  0.13414033],
       [-0.68911076, -1.95722334],
       [-0.52979606,  1.67634486],
       [-1.13010991,  0.52760277],
       [ 0.87815724,  0.447865  ],
       [-0.02734585, -0.41572127],
       [-1.4621875 , -0.6240712 ],
       [-0.17635855,  2.0013916 ],
       [ 0.23521487,  0.27342547],
       [-0.11497086,  1.97714563]])

In [81]:
np.random.randint(0,10,3)

array([1, 3, 6])

In [86]:
a.reshape(2,3)

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [6]:
my_arr = [[1,2,3], [4,5,6], [7,8,9]]
aab = np.array(my_arr)
aab

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
ada = np.arange(1,10)
ada.reshape(3,3) * 0

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [33]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [34]:
aaa = np.arange(1 , 11)

In [35]:
aaa

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
aaa ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)