In [1]:
import numpy

In [23]:
n = numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [11]:
type(n)

numpy.ndarray

In [12]:
help(numpy)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [24]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [1]:
import cv2

In [14]:
grey= cv2.imread("smallgray.png",0)

In [15]:
print(grey)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [9]:
cv2.imwrite("new.png",grey)

True

In [18]:
for i in grey:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [19]:
grey

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [20]:
import numpy

In [21]:
gg = numpy.hstack((grey,grey))

In [22]:
gg

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [23]:
gg = numpy.vstack((grey,grey))
gg

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [39]:
gg = numpy.hsplit(grey,5)

In [37]:
print(gg)

[array([[187],
       [198],
       [209]], dtype=uint8), array([[158],
       [125],
       [134]], dtype=uint8), array([[104],
       [255],
       [255]], dtype=uint8), array([[121],
       [255],
       [ 97]], dtype=uint8), array([[143],
       [147],
       [182]], dtype=uint8)]


In [35]:
grey

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)